### ISSUE TITLE
Use physical-cpu-count

### ISSUE THREAD

**Issue by aleclarson** [Aslemammad/tinypool#18]
https://www.npmjs.com/package/physical-cpu-count

> Working with clusters of Node.js processes it is common to see code using `os.cpus().length` as the number of child workers to fork. For some workloads this can negatively impact performance on CPUs that use simultaneous multithreading (SMT). Latency is doubled because two processes share the same physical CPU core to get their work done. Additionally there is memory spent for each running worker, as well as time to spawn their processes. It is better to fork no more child processes than there are physical cores.

**Comment by Aslemammad** [comment]
Oh, thank you for your issues. If you are interested in sending a PR, feel free. if not, I can take it!

**Comment by aleclarson** [comment]
You can take this one 😊

**Comment by Aslemammad** [comment]
Sure, I'll release in minutes if possible!

**Comment by Aslemammad** [comment]
Released in v0.0.8
