### ISSUE TITLE
Add `isWorkerThread` export

### ISSUE THREAD

**Issue by aleclarson** [Aslemammad/tinypool#19]
https://github.com/piscinajs/piscina#static-property-isworkerthread-readonly

I run an instance of my worker in the main thread, and it needs to know when that's the case.

Piscina has an `isWorkerThread` export. Should this library have that too?

**Comment by Aslemammad** [comment]
We have already exported it.

```ts
import Tinypool from 'tinypool'

test('isWorkerThread correct value', async () => {
  expect(Tinypool.isWorkerThread).toBe(false)
})
```
