### ISSUE TITLE
More tests

### ISSUE THREAD

**Issue by Aslemammad** [Aslemammad/tinypool#2]
It'd be good if we bring more tests from https://github.com/piscinajs/piscina/tree/current/test into tinypool.

**Comment by tigerabrodi** [comment]
@Aslemammad 

Big boss, just assigned it to me :pray: :orange_heart: :raised_hands: 

![08bf8-16321313916558-800](https://user-images.githubusercontent.com/49603590/147383991-0acc501d-5d23-4ed5-ae50-0a90ecd77fb1.jpg)

**Comment by Aslemammad** [comment]
@Sajad-Sharhani you two can split tests for you & send PRs for them! 
Thanks to @Sajad-Sharhani & @tigerabrodi
